# DATABASE

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/testdatabase
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  file:
    name: logging.log